export enum Glyph {
  Vue = "vue",
  Video = "video",
  Triangle = "triangle",
  Test = "test",
  Tag = "tag",
  Table = "table",
  Svelte = "svelte",
  Shield = "shield",
  Shell = "shell",
  Settings = "settings",
  RootFolder = "root_folder",
  RootFolderExpanded = "root_folder_expanded",
  React = "react",
  Prisma = "prisma",
  Parenthesis = "parenthesis",
  OpenSource = "open_source",
  Next = "next",
  Microsoft = "microsoft",
  Merge = "merge",
  Lock = "lock",
  Information = "information",
  Image = "image",
  I18n = "i18n",
  History = "history",
  Git = "git",
  Gatsby = "gatsby",
  Format = "format",
  Folder = "folder",
  FolderExpanded = "folder_expanded",
  Fingerprint = "fingerprint",
  File = "file",
  Expo = "expo",
  Eslint = "eslint",
  Document = "document",
  Docs = "docs",
  Database = "database",
  Copyright = "copyright",
  Commit = "commit",
  Certificate = "certificate",
  Camera = "camera",
  Brackets = "brackets",
  Braces = "braces",
  Audio = "audio",
  Archive = "archive",
  Angular = "angular",
}

export const GLYPH_CODEPOINTS: { [key in Glyph]: string } = {
  [Glyph.Vue]: "61697",
  [Glyph.Video]: "61698",
  [Glyph.Triangle]: "61699",
  [Glyph.Test]: "61700",
  [Glyph.Tag]: "61701",
  [Glyph.Table]: "61702",
  [Glyph.Svelte]: "61703",
  [Glyph.Shield]: "61704",
  [Glyph.Shell]: "61705",
  [Glyph.Settings]: "61706",
  [Glyph.RootFolder]: "61707",
  [Glyph.RootFolderExpanded]: "61708",
  [Glyph.React]: "61709",
  [Glyph.Prisma]: "61710",
  [Glyph.Parenthesis]: "61711",
  [Glyph.OpenSource]: "61712",
  [Glyph.Next]: "61713",
  [Glyph.Microsoft]: "61714",
  [Glyph.Merge]: "61715",
  [Glyph.Lock]: "61716",
  [Glyph.Information]: "61717",
  [Glyph.Image]: "61718",
  [Glyph.I18n]: "61719",
  [Glyph.History]: "61720",
  [Glyph.Git]: "61721",
  [Glyph.Gatsby]: "61722",
  [Glyph.Format]: "61723",
  [Glyph.Folder]: "61724",
  [Glyph.FolderExpanded]: "61725",
  [Glyph.Fingerprint]: "61726",
  [Glyph.File]: "61727",
  [Glyph.Expo]: "61728",
  [Glyph.Eslint]: "61729",
  [Glyph.Document]: "61730",
  [Glyph.Docs]: "61731",
  [Glyph.Database]: "61732",
  [Glyph.Copyright]: "61733",
  [Glyph.Commit]: "61734",
  [Glyph.Certificate]: "61735",
  [Glyph.Camera]: "61736",
  [Glyph.Brackets]: "61737",
  [Glyph.Braces]: "61738",
  [Glyph.Audio]: "61739",
  [Glyph.Archive]: "61740",
  [Glyph.Angular]: "61741",
};
