// DO NOT MODIFY this file, extend it instead

import legacyMinimal from "./legacy-minimal";
import { createIconSetBuilder } from "../build/iconsets";

/**
 * @module legacyOriginal
 * @description The original icon set from Spectrum Icons
 */
export default createIconSetBuilder({
  extend: legacyMinimal(),
  icons: [
    [
      "angular",
      [
        "fileExtensions",
        "component.js",
        "component.ts",
        "directive.js",
        "directive.ts",
        "filter.js",
        "guard.js",
        "guard.ts",
        "module.js",
        "module.ts",
        "ng-template",
        "pipe.js",
        "pipe.ts",
        "resolver.js",
        "resolver.ts",
        "service.js",
        "service.ts",
      ],
      ["fileNames", "angular-cli.json", "angular.json"],
    ],
    [
      "archive",
      [
        "fileExtensions",
        "7z",
        "br",
        "brotli",
        "bzip2",
        "gz",
        "gzip",
        "rar",
        "tar",
        "tgz",
        "xz",
        "zip",
      ],
    ],
    ["audio", ["fileExtensions", "aiff", "flac", "m4a", "mp3", "wav", "wma"]],
    [
      "braces",
      ["fileExtensions", "js"],
      [
        "languageIds",
        "c",
        "coffeescript",
        "cpp",
        "csharp",
        "css",
        "fsharp",
        "go",
        "groovy",
        "handlebars",
        "html",
        "jade",
        "java",
        "javascript",
        "javascriptreact",
        "less",
        "lua",
        "objective-c",
        "perl",
        "php",
        "properties",
        "python",
        "ruby",
        "rust",
        "scss",
        "swift",
        "typescript",
        "typescriptreact",
        "xml",
        "yaml",
      ],
    ],
    ["brackets", ["fileExtensions", "htm", "html", "xml"]],
    ["camera", ["fileExtensions", "snap"]],
    [
      "certificate",
      ["fileExtensions", "cer", "cert", "crt"],
      [
        "fileNames",
        "licence",
        "licence.md",
        "licence.txt",
        "license",
        "license.md",
        "license.txt",
        "unlicense",
        "unlicense.md",
        "unlicense.txt",
      ],
    ],
    ["copyright", ["fileNames", "authors", "authors.md", "authors.txt"]],
    [
      "database",
      ["fileExtensions", "graphql", "json", "sqlite"],
      ["languageIds", "json", "sql"],
    ],
    ["docs", ["fileExtensions", "md", "mdx"], ["languageIds", "markdown"]],
    [
      "document",
      ["fileExtensions", "doc", "docx", "pdf", "ppt", "pptx", "rtf", "txt"],
      [
        "fileNames",
        "_headers",
        "_redirects",
        ".htaccess",
        "robots.txt",
        "sitemap.xml",
      ],
    ],
    [
      "fingerprint",
      ["fileExtensions", "asc", "gpg", "key", "pem", "pub"],
      ["fileNames", ".htpasswd"],
    ],
    [
      "format",
      [
        "fileNames",
        ".prettierignore",
        ".prettierrc",
        ".prettierrc.js",
        ".prettierrc.json",
        ".prettierrc.yaml",
        ".prettierrc.yml",
        "prettier.config.js",
      ],
    ],
    [
      "gatsby",
      [
        "fileNames",
        "gatsby-browser.js",
        "gatsby-config.js",
        "gatsby-node.js",
        "gatsby-ssr.js",
      ],
    ],
    [
      "git",
      ["fileExtensions", "patch"],
      [
        "fileNames",
        ".git-history",
        ".gitattributes",
        ".gitconfig",
        ".gitignore",
        ".gitkeep",
        ".gitmodules",
      ],
    ],
    [
      "history",
      [
        "fileNames",
        "changelog",
        "changelog.md",
        "changelog.txt",
        "changes",
        "changes.md",
        "changes.txt",
      ],
    ],
    ["i18n", ["fileExtensions", "mo", "po", "pot"]],
    [
      "image",
      [
        "fileExtensions",
        "bmp",
        "eps",
        "gif",
        "ico",
        "img",
        "jpeg",
        "jpg",
        "png",
        "psd",
        "raw",
        "svg",
        "tif",
        "tiff",
        "webp",
      ],
    ],
    [
      "information",
      ["fileExtensions", "log"],
      ["fileNames", "readme", "readme.md", "readme.txt"],
    ],
    [
      "lock",
      ["fileExtensions", "lock"],
      ["fileNames", "security", "security.md", "security.txt"],
    ],
    [
      "microsoft",
      [
        "fileExtensions",
        "code-workplace",
        "csproj",
        "ruleset",
        "sln",
        "suo",
        "vb",
        "vbs",
        "vcxitems",
        "vcxitems.filters",
        "vcxproj",
        "vcxproj.filters",
        "vscodeignore",
        "vsix",
        "vsixmanifest",
      ],
    ],
    [
      "open-source",
      ["fileNames", "contributing.md", "credits", "credits.md", "credits.txt"],
    ],
    [
      "parenthesis",
      ["fileExtensions", "cl", "el", "elc", "fasl", "l", "lisp", "lsp", "wat"],
      ["languageIds", "clojure"],
    ],
    ["react", ["fileExtensions", "jsx", "tsx"]],
    [
      "settings",
      [
        "fileExtensions",
        "cfg",
        "conf",
        "config",
        "dlc",
        "dll",
        "env",
        "env.example",
        "ini",
        "option",
        "prefs",
        "prop",
        "properties",
        "props",
        "settings",
        "sln.dotsettings",
        "sln.dotsettings.user",
        "toml",
      ],
      [
        "fileNames",
        ".buildignore",
        ".clang-format",
        ".clang-tidy",
        ".jshintignore",
        ".mrconfig",
        ".yardopts",
        "manifest.mf",
        "package.json",
      ],
      ["languageIds", "makefile"],
    ],
    [
      "shell",
      ["fileExtensions", "awk", "fish", "tcsh", "zshrc"],
      ["languageIds", "bat", "powershell", "shellscript"],
    ],
    [
      "shield",
      [
        "fileNames",
        ".eslintcache",
        ".eslintignore",
        ".eslintrc",
        ".eslintrc.cjs",
        ".eslintrc.js",
        ".eslintrc.json",
        ".eslintrc.yaml",
        ".eslintrc.yml",
      ],
    ],
    ["table", ["fileExtensions", "csv", "tsv", "xls", "xlsx"]],
    ["tag", ["fileExtensions", "css", "less", "sass", "scss", "styl"]],
    [
      "test",
      [
        "fileExtensions",
        "e2e-spec.js",
        "e2e-spec.ts",
        "js.snap",
        "jsx.snap",
        "spec.js",
        "spec.jsx",
        "spec.ts",
        "spec.tsx",
        "test.js",
        "test.jsx",
        "test.ts",
        "test.tsx",
        "ts.snap",
        "tsx.snap",
      ],
    ],
    [
      "video",
      [
        "fileExtensions",
        "avi",
        "m2v",
        "m4v",
        "mkv",
        "mov",
        "mp4",
        "mpeg",
        "mpg",
        "mpv",
        "webm",
        "wmv",
      ],
    ],
    [
      "vue",
      ["fileExtensions", "store.js", "store.ts", "vue"],
      [
        "fileNames",
        "nuxt.config.js",
        "nuxt.config.ts",
        "store.js",
        "store.ts",
        "vue.config.js",
        "vue.config.ts",
      ],
    ],
  ],
});
